//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakalelerManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int KullaniciID { get; set; }
        public string KullaniciAd { get; set; }
        public string KullaniciSifre { get; set; }
        public string role { get; set; }
        public Nullable<int> PersonelID { get; set; }
    
        public virtual Personeller Personeller { get; set; }
    }
}
